package com.github.wdeqin.flyit.web;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'wdeqin' at '7/30/16 9:28 AM' with Gradle 2.14
 *
 * @author wdeqin, @date 7/30/16 9:28 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
