package com.github.wdeqin.flyit.data.model;

public class Seq {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_seq_t.seqnam
     *
     * @mbggenerated Thu Sep 01 21:43:58 CST 2016
     */
    private String seqnam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_seq_t.nxtval
     *
     * @mbggenerated Thu Sep 01 21:43:58 CST 2016
     */
    private Integer nxtval;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_seq_t.seqnam
     *
     * @return the value of dev_seq_t.seqnam
     *
     * @mbggenerated Thu Sep 01 21:43:58 CST 2016
     */
    public String getSeqnam() {
        return seqnam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_seq_t.seqnam
     *
     * @param seqnam the value for dev_seq_t.seqnam
     *
     * @mbggenerated Thu Sep 01 21:43:58 CST 2016
     */
    public void setSeqnam(String seqnam) {
        this.seqnam = seqnam == null ? null : seqnam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_seq_t.nxtval
     *
     * @return the value of dev_seq_t.nxtval
     *
     * @mbggenerated Thu Sep 01 21:43:58 CST 2016
     */
    public Integer getNxtval() {
        return nxtval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_seq_t.nxtval
     *
     * @param nxtval the value for dev_seq_t.nxtval
     *
     * @mbggenerated Thu Sep 01 21:43:58 CST 2016
     */
    public void setNxtval(Integer nxtval) {
        this.nxtval = nxtval;
    }
}